@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":SortCommandParser" as SortCommandParser LOGIC_COLOR
participant "s:SortCommand" as SortCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("sort by/name asc")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("sort by/name asc")
activate AddressBookParser

create SortCommandParser
AddressBookParser -> SortCommandParser
activate SortCommandParser

SortCommandParser --> AddressBookParser
deactivate SortCommandParser

AddressBookParser -> SortCommandParser : parse("by/name asc")
activate SortCommandParser

create SortCommand
SortCommandParser -> SortCommand : SortCommand("name", true)
activate SortCommand

SortCommand --> SortCommandParser
deactivate SortCommand

SortCommandParser --> AddressBookParser : s
deactivate SortCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
SortCommandParser -[hidden]-> AddressBookParser
destroy SortCommandParser

AddressBookParser --> LogicManager : s
deactivate AddressBookParser

LogicManager -> SortCommand : execute(m)
activate SortCommand

SortCommand -> Model : getFilteredPersonList()
activate Model
Model --> SortCommand : persons
deactivate Model

SortCommand -> SortCommand : persons.sort(comparator)
activate SortCommand #DarkSalmon
deactivate SortCommand

SortCommand -> Model : setAddressBook(newAddressBook)
activate Model
Model --> SortCommand
deactivate Model

create CommandResult
SortCommand -> CommandResult : CommandResult(message)
activate CommandResult
CommandResult --> SortCommand
deactivate CommandResult

SortCommand --> LogicManager : r
deactivate SortCommand

[<--LogicManager : r
deactivate LogicManager
@enduml
